enum EEvents {
	PROCESSING_START = "PROCESSING_START",
	PROCESSING_END = "PROCESSING_END",
	PROCESSING_SUCCESS = "PROCESSING_SUCCESS",
	PROCESSING_ERROR = "PROCESSING_ERROR",
	CLEARED = "CLEARED",
	BEFORE_CLEARE = "BEFORE_CLEARE",
	START = "START",
	PAUSE = "PAUSE",
	WAITING_NEW_DATAS = "WAITING_NEW_DATAS",
}

export default EEvents;
