enum EEvents {
	PROCESSING_STARTED = "PROCESSING_STARTED",
	PROCESSING_ENDED = "PROCESSING_ENDED",
	PROCESSING_SUCCESSED = "PROCESSING_SUCCESSED",
	PROCESSING_ERRORED = "PROCESSING_ERRORED",
	CLEARED = "CLEARED",
	WILL_CLEARED = "WILL_CLEARED",
	STARTED = "STARTED",
	PAUSED = "PAUSED",
	WAITING_NEW_DATAS = "WAITING_NEW_DATAS",
}

export default EEvents;
